import '~/styles/globals.css';

import localFont from 'next/font/local';
import { type Metadata } from 'next';

import { ClerkProvider } from '@clerk/nextjs';

import { TRPCReactProvider } from '~/trpc/react';
import { ThemeProvider } from '~/context/theme-provider';

export const metadata: Metadata = {
  title: 'Designer Impact',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const neueMontreal = localFont({
  src: [
    {
      path: './fonts/PPNeueMontreal-Thin.otf',
      weight: '300',
      style: 'thin',
    },
    {
      path: './fonts/PPNeueMontreal-Medium.otf',
      weight: '500',
      style: 'medium',
    },
    {
      path: './fonts/PPNeueMontreal-SemiBolditalic.otf',
      weight: '600',
      style: 'semibold',
    },

    {
      path: './fonts/PPNeueMontreal-Bold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang='en' className={`${neueMontreal.className}`} suppressHydrationWarning>
        <body>
          <ThemeProvider attribute='class' defaultTheme='dark' disableTransitionOnChange>
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
